{
  "cve_id": "CVE-2015-5159",
  "github_data": {
    "repository": "latchset/kdcproxy",
    "fix_commit": "f274aa6787cb8b3ec1cc12c440a56665b7231882",
    "related_commits": [
      "f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "f274aa6787cb8b3ec1cc12c440a56665b7231882"
    ],
    "patch_url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882.patch",
    "fix_commit_details": {
      "sha": "f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "commit_date": "2015-08-03T18:38:49Z",
      "author": {
        "login": "npmccallum",
        "type": "User",
        "stats": null
      },
      "commit_message": {
        "title": "Enforce a maximum packet length",
        "length": 86,
        "has_description": true,
        "references_issue": true
      },
      "stats": {
        "total": 7,
        "additions": 6,
        "deletions": 1
      },
      "files": [
        {
          "filename": "kdcproxy/__init__.py",
          "status": "modified",
          "additions": 6,
          "deletions": 1,
          "patch": "@@ -61,6 +61,7 @@ def __str__(self):\n \n \n class Application:\n+    MAX_LENGTH = 128 * 1024\n     SOCKTYPES = {\n         \"tcp\": socket.SOCK_STREAM,\n         \"udp\": socket.SOCK_DGRAM,\n@@ -180,7 +181,11 @@ def __call__(self, env, start_response):\n             try:\n                 length = int(env[\"CONTENT_LENGTH\"])\n             except AttributeError:\n-                length = -1\n+                raise HTTPException(411, \"Length required.\")\n+            if length < 0:\n+                raise HTTPException(411, \"Length required.\")\n+            if length > self.MAX_LENGTH:\n+                raise HTTPException(413, \"Request entity too large.\")\n             try:\n                 pr = codec.decode(env[\"wsgi.input\"].read(length))\n             except codec.ParsingError as e:"
        }
      ],
      "file_patterns": {
        "security_files": 0,
        "config_files": 0,
        "dependency_files": 0,
        "test_files": 0,
        "unique_directories": 1,
        "max_directory_depth": 1
      },
      "context": {
        "surrounding_commits": [
          {
            "sha": "0606ca5a9002ab85c1624639206fee4abbd8c0eb",
            "date": "2024-11-22T10:44:52Z",
            "author_login": "jrisc"
          },
          {
            "sha": "e312870038cfbe1ff27d5c2945157166c0caeedd",
            "date": "2024-11-18T09:01:16Z",
            "author_login": "jrisc"
          },
          {
            "sha": "2075b09611c24b67e87ec8cc04c2a124fce6f9a6",
            "date": "2024-11-18T08:38:13Z",
            "author_login": "jrisc"
          },
          {
            "sha": "f61979eca217e53062a90344d6ab853695318089",
            "date": "2024-03-13T21:01:32Z",
            "author_login": "simo5"
          },
          {
            "sha": "8df33b647d4829b0cae65ea94a57c30d9424f4a2",
            "date": "2021-08-12T16:37:02Z",
            "author_login": "frozencemetery"
          }
        ]
      }
    }
  },
  "vulnerability_details": {
    "cvss_score": null,
    "cvss_vector": null,
    "cwe_id": "CWE-20",
    "description": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.",
    "attack_vector": null,
    "attack_complexity": null
  },
  "temporal_data": {
    "published_date": "2018-10-30T18:29:00.207",
    "last_modified": "2024-11-21T02:32:28.250",
    "fix_date": "2015-08-03T18:38:49Z"
  },
  "references": [
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200",
      "source": "secalert@redhat.com",
      "tags": [
        "Issue Tracking",
        "Mitigation",
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "source": "secalert@redhat.com",
      "tags": [
        "Patch",
        "Vendor Advisory"
      ]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Issue Tracking",
        "Mitigation",
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch",
        "Vendor Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T22:59:38.541201",
    "processing_status": "raw"
  },
  "repository_context": {
    "name": "kdcproxy",
    "owner": "latchset",
    "created_at": "2014-01-16T18:39:59Z",
    "updated_at": "2025-01-03T18:53:03Z",
    "pushed_at": "2024-11-22T15:02:55Z",
    "size": 81,
    "stars": 62,
    "forks": 22,
    "open_issues": 6,
    "watchers": 62,
    "has_security_policy": false,
    "default_branch": "main",
    "protected_branches": [
      "main"
    ],
    "languages": {
      "Python": 54835
    },
    "commit_activity": {
      "total_commits_last_year": 0,
      "avg_commits_per_week": 0,
      "days_active_last_year": 0
    },
    "security_features": {
      "has_security_policy": false,
      "has_protected_branches": true,
      "has_wiki": false,
      "has_issues": true,
      "allow_forking": true,
      "is_template": false,
      "license": "mit"
    },
    "collected_at": "2025-01-14T17:19:09.489683"
  }
}