{
  "cve_id": "CVE-2021-23338",
  "github_data": {
    "repository": "418sec/huntr",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 6.6,
    "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:H",
    "cwe_id": "CWE-502",
    "description": "This affects all versions of package qlib. The workflow function in cli part of qlib was using an unsafe YAML load function.",
    "attack_vector": "NETWORK",
    "attack_complexity": "HIGH"
  },
  "temporal_data": {
    "published_date": "2021-02-15T16:15:15.263",
    "last_modified": "2024-11-21T05:51:31.840",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/418sec/huntr/pull/1329",
      "source": "report@snyk.io",
      "tags": [
        "Exploit",
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://snyk.io/vuln/SNYK-PYTHON-QLIB-1054635",
      "source": "report@snyk.io",
      "tags": [
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/418sec/huntr/pull/1329",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Exploit",
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://snyk.io/vuln/SNYK-PYTHON-QLIB-1054635",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Third Party Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:01:16.788136",
    "processing_status": "enhanced"
  }
}