{
  "cve_id": "CVE-2020-8545",
  "github_data": {
    "repository": "CIRCL/AIL-framework",
    "fix_commit": "e808840f957c810b8e3944cba808716dc722581b",
    "related_commits": [
      "e808840f957c810b8e3944cba808716dc722581b",
      "e808840f957c810b8e3944cba808716dc722581b"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 7.5,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    "cwe_id": "CWE-22",
    "description": "Global.py in AIL framework 2.8 allows path traversal.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2020-02-03T16:15:11.997",
    "last_modified": "2024-11-21T05:39:00.483",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/CIRCL/AIL-framework/commit/e808840f957c810b8e3944cba808716dc722581b",
      "source": "cve@mitre.org",
      "tags": [
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/CIRCL/AIL-framework/commit/e808840f957c810b8e3944cba808716dc722581b",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch",
        "Third Party Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:00:37.508599",
    "processing_status": "raw"
  }
}