{
  "cve_id": "CVE-2018-19194",
  "github_data": {
    "repository": "AvaterXXX/XiaoCms",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": null,
    "cvss_vector": null,
    "cwe_id": "CWE-200",
    "description": "An issue was discovered in XiaoCms 20141229. /admin/index.php?c=database allows full path disclosure in a \"failed to open stream\" error message.",
    "attack_vector": null,
    "attack_complexity": null
  },
  "temporal_data": {
    "published_date": "2018-11-12T05:29:00.340",
    "last_modified": "2024-11-21T03:57:31.333",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/AvaterXXX/XiaoCms/blob/master/INFO_EXP.md",
      "source": "cve@mitre.org",
      "tags": [
        "Exploit",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/AvaterXXX/XiaoCms/blob/master/INFO_EXP.md",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Exploit",
        "Third Party Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T22:59:38.555008",
    "processing_status": "raw"
  }
}