{
  "cve_id": "CVE-2024-39705",
  "github_data": {
    "repository": "nltk/nltk",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 9.8,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "cwe_id": "CWE-502",
    "description": "NLTK through 3.8.1 allows remote code execution if untrusted packages have pickled Python code, and the integrated data package download functionality is used. This affects, for example, averaged_perceptron_tagger and punkt.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2024-06-27T22:15:10.543",
    "last_modified": "2024-11-21T09:28:15.537",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/nltk/nltk/issues/2522",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://github.com/nltk/nltk/issues/3266",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://www.vicarius.io/vsociety/posts/rce-in-python-nltk-cve-2024-39705-39706",
      "source": "cve@mitre.org",
      "tags": []
    },
    {
      "url": "https://github.com/nltk/nltk/issues/2522",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    },
    {
      "url": "https://github.com/nltk/nltk/issues/3266",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    },
    {
      "url": "https://www.vicarius.io/vsociety/posts/rce-in-python-nltk-cve-2024-39705-39706",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:08:28.869407",
    "processing_status": "raw"
  }
}